config/routes.rb
Rails.application.routes.draw do

  resources :orders, except: [:show, :edit] do
    get 'historic', on: :collection
    get 'pay', on: :member
  end

  resources :products

  resources :customers

  root 'dashboard#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  has_many :products, through: :orders
  
  validates :name, presence: true
  
  
  def total_debt
    self.orders.unpaid.inject(0.0) { |sum, order| sum += order.total_cost  }
  end
  
  def total_income
    self.orders.paid.inject(0.0) { |sum, order| sum += order.total_cost  }
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @orders = @customer.orders
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer_table.html.erb
<div class="table-responsive">
  <table class="table table-stripped">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Órdenes totales</th>
        <th>No pagadas</th>
        <th>Ingreso generado</th>
        <th>Deuda total</th>
        <th colspan="1"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
            <td><%= link_to customer.name, customer %></td>
            <td><%= customer.orders.count %></td>
            <td><%= customer.orders.unpaid.count %></td>
            <td>$<%= customer.total_income %></td>
            <td>$<%= customer.total_debt %></td>
            <td>
                <div class="btn-group btn-group-xs" role="group">
                  <%= link_to customer, class: 'btn btn-default' do %>
                      <%= icon 'user' %> Ver perfil
                  <% end %>
                </div>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= f.submit 'Guardar cliente', class: 'btn btn-primary' %>
      <%= link_to 'Cancelar', customers_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h3>Editar cliente</h3>

<%= render 'form' %>

app/views/customers/index.html.erb
<h3>Clientes</h3>
<%= render 'customers/customer_table' %>

app/views/customers/new.html.erb
<h3>Nuevo cliente</h3>

<%= render 'form' %>

app/views/customers/show.html.erb
<h3><%= @customer.name %></h3>
<div class="row">
  <div class="col-md-6">
    <div class="table-responsive">
      <table class="table">
        <tr>
          <td><%= icon 'shopping-cart'  %> <strong>Ventas totales:</strong></td>
          <td><%= @customer.orders.count %></td>
        </tr>
        <tr>
          <td><%= icon 'check-square-o'  %> <strong>Ventas pagadas:</strong></td>
          <td><%= @customer.orders.paid.count %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="col-md-6">
    <div class="table-responsive">
      <table class="table">
        <tr>
          <td><%= icon 'money'  %> <strong>Ingresos generados:</strong></td>
          <td>$<%= @customer.total_income %></td>
        </tr>
        <tr>
          <td><%= icon 'exclamation-triangle'  %> <strong>Deuda total:</strong></td>
          <td>$<%= @customer.total_debt %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h3>Órdenes</h3>
    <%= render 'orders/order_table' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="btn-group" role="group">
      <%= link_to edit_customer_path(@customer), class: 'btn btn-primary' do %>
          <%= icon 'pencil-square-o' %> Editar
      <% end %>
      <%= link_to customers_path, class: 'btn btn-default' do %>
          <%= icon 'users' %> Volver
      <% end %>
      <%= link_to customer_path(@customer), class: 'btn btn-default', method: :delete, data: { confirm: '¿Estas seguro?' } do %>
          <%= icon 'trash-o' %> Eliminar
      <% end %>
    </div>
  </div>
</div>