config/routes.rb
Rails.application.routes.draw do

  resources :orders, except: [:show, :edit] do
    get 'historic', on: :collection
    get 'pay', on: :member
  end

  resources :products

  resources :customers

  root 'dashboard#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :product
  
  validates :product_id, presence: true
  validates :customer_id, presence: true
  validates :quantity, inclusion: { in: (1..20) }
  
  before_create :calculate_total_cost
  
  scope :latest, -> { order 'created_at DESC' }
  scope :paid, -> { where paid: true }
  scope :unpaid, -> { where paid: false }
  
  def pay
    self.paid = true
    self.save
  end
  
  
  private
    def calculate_total_cost
      self.total_cost = self.quantity * self.product.price
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :pay, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.unpaid.latest
  end
  
  # GET /orders/historic
  # GET /orders/historic.json
  def historic
    @orders = Order.paid.latest
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end
  
  # GET /orders/1/pay
  def pay
    @order.pay
    redirect_to orders_url, notice: 'La orden fue pagada.'
  end  

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_redirect_path(@order), notice: 'La orden fue creada.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_redirect_path(@order), notice: 'La orden fue actualizada.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'La orden fue eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:quantity, :customer_id, :product_id, :paid)
    end
    
    # Determines the path to redirect according to the payment status of the given order
    def order_redirect_path(order)
      order.paid? ? historic_orders_path : orders_path
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <strong><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</strong>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :producto, class: 'control-label' %>
        <%= f.select :product_id, Product.all.map{ |p| [p.name, p.id ] }, { include_blank: false }, { class: 'form-control' } %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :cantidad, class: 'control-label' %>
        <%= f.number_field :quantity, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :cliente, class: 'control-label' %>
        <%= f.select :customer_id, Customer.all.map{ |c| [c.name, c.id ] }, { include_blank: false }, { class: 'form-control' } %>
      </div>
      <div class="checkbox">
        <label> <%= f.check_box :paid %> Pagado </label>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= f.submit 'Guardar orden', class: 'btn btn-primary' %>
      <%= link_to 'Cancelar', orders_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/orders/_order_table.html.erb
<div class="table-responsive">
  <table class="table table-stripped">
    <thead>
      <tr>
        <th>Valor Total</th>
        <th>Cantidad</th>
        <th>Cliente</th>
        <th>Producto</th>
        <th colspan="1"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @orders.each do |order| %>
        <tr>
            <td>$ <%= order.total_cost %></td>
            <td><%= order.quantity %></td>
            <td><%= link_to order.customer.name, order.customer %></td>
            <td><%= link_to order.product.name, order.product %></td>
            <td>
                <div class="btn-group btn-group-xs" role="group">
                  <% unless order.paid? %>
                    <%= link_to pay_order_path(order), class: 'btn btn-primary btn-xs' do %>
                        <%= icon 'check-square-o' %> Pagar
                    <% end %>
                  <% end %>
                  <%= link_to order_path(order), class: 'btn btn-default', method: :delete, data: { confirm: '¿Estas seguro?' } do %>
                      <%= icon 'trash-o' %> Eliminar
                  <% end %>
                </div>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/_stats.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Resumen</h3>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
        <table class="table">
            <tr>
                <td><%= icon 'shopping-cart'  %> <strong>Ventas Totales:</strong></td>
                <td><%= Order.count %></td>
            </tr>
            <tr>
                <td><%= icon 'check-square-o'  %> <strong>Ventas pagadas:</strong></td>
                <td><%= Order.paid.count %></td>
            </tr>
            <tr>
                <td><%= icon 'money'  %> <strong>Ingresos Totales:</strong></td>
                <td>$ <%= OrderCalculator.paid_total %></td>
            </tr>
            <tr>
                <td><%= icon 'exclamation-triangle'  %> <strong>Deuda Total:</strong></td>
                <td>$ <%= OrderCalculator.unpaid_total %></td>
            </tr>
        </table>
    </div>
    
  </div>
</div>

app/views/orders/_unpaid.html.erb
<h3>Órdenes no pagadas</h3>

<div class="table-responsive">
  <table class="table table-stripped">
    <thead>
      <tr>
        <th>Valor Total</th>
        <th>Cantidad</th>
        <th>Cliente</th>
        <th>Producto</th>
        <th colspan="1"></th>
        <th colspan="1"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @orders.each do |order| %>
        <tr>
            <td>$ <%= order.total_cost %></td>
            <td><%= order.quantity %></td>
            <td><%= link_to order.customer.name, order.customer %></td>
            <td><%= link_to order.product.name, order.product %></td>
            <td>
                <%= link_to pay_order_path(order), class: 'btn btn-primary btn-xs' do %>
                    <%= icon 'check-square-o' %> Pagar
                <% end %>
                <div class="btn-group btn-group-xs" role="group" aria-label="...">
            </td>
            <td>
                <div class="btn-group btn-group-xs" role="group" aria-label="...">
                  <%= link_to edit_order_path(order), class: 'btn btn-default' do %>
                      <%= icon 'pencil-square-o' %> Editar
                  <% end %>
                  <%= link_to edit_order_path(order), class: 'btn btn-default', method: :delete, data: { confirm: '¿Estas seguro?' } do %>
                      <%= icon 'trash-o' %> Eliminar
                  <% end %>
                </div>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/historic.html.erb
<h3>Órdenes pagadas</h3>
<%= render 'orders/order_table' %>

app/views/orders/index.html.erb
<h3>Órdenes no pagadas</h3>
<%= render 'orders/order_table' %>

app/views/orders/new.html.erb
<h3>Nueva orden</h3>

<%= render 'form' %>