config/routes.rb
Rails.application.routes.draw do

  resources :orders, except: [:show, :edit] do
    get 'historic', on: :collection
    get 'pay', on: :member
  end

  resources :products

  resources :customers

  root 'dashboard#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :customers, through: :orders
  
  validates :name, presence: true
  validates :description, length: { maximum: 1000 }, presence: true
  validates :price, presence: true, numericality: {greater_than: 0}
  validates :image, presence: true
  
  def total_sales
    self.orders.inject(0) { |sum, order| sum += order.quantity  }
  end
  
  def total_income
    self.orders.paid.inject(0) { |sum, order| sum += order.total_cost  }
  end
  
  def total_debt
    self.orders.unpaid.inject(0) { |sum, order| sum += order.total_cost  }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @orders = @product.orders
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :descripcion %>
    <%= f.text_area :description, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :precio %>
    <%= f.text_field :price, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :imagen %>
    <%= f.text_field :image, class: 'form-control'  %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= f.submit 'Guardar producto', class: 'btn btn-primary' %>
      <%= link_to 'Cancelar', products_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/products/_product_table.html.erb
<div class="table-responsive">
  <table class="table table-stripped">
    <thead>
      <tr>
        <th colspan="1"></th>
        <th>Nombre</th>
        <th>Ventas totales</th>
        <th>Ingreso generado</th>
        <th>Deuda total</th>
        <th colspan="1"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @products.each do |product| %>
        <tr>
            <td>
                <%= link_to product do %>
                    <%= image_tag product.image, class: 'img-responsive img-rounded', size: '48x48' %> 
                <% end %>
            </td>
            <td><%= link_to product.name, product %></td>
            <td><%= product.total_sales %></td>
            <td>$<%= product.total_income %></td>
            <td>$<%= product.total_debt %></td>
            <td>
                <div class="btn-group btn-group-xs" role="group">
                  <%= link_to product, class: 'btn btn-default' do %>
                      <%= icon 'cutlery' %> Ver detalles
                  <% end %>
                </div>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/edit.html.erb
<h3>Editar producto</h3>

<%= render 'form' %>

app/views/products/index.html.erb
<h3>Productos</h3>
<%= render 'products/product_table' %>

app/views/products/new.html.erb
<h3>Nuevo producto</h3>

<%= render 'form' %>

app/views/products/show.html.erb
<h3><%= @product.name %></h3>
<p class="lead">
  <%= @product.description %>
</p>
<div class="row">
  <div class="col-md-4">
    <%= image_tag @product.image, class: 'img-responsive img-rounded' %>
  </div>
  <div class="col-md-8">
    <div class="table-responsive">
      <table class="table">
        <tr>
          <td><%= icon 'dollar'  %> <strong>Precio:</strong></td>
          <td>$<%= @product.price %></td>
        </tr>
        <tr>
          <td><%= icon 'shopping-cart'  %> <strong>Ventas totales:</strong></td>
          <td><%= @product.orders.count %></td>
        </tr>
        <tr>
          <td><%= icon 'check-square-o'  %> <strong>Ventas pagadas:</strong></td>
          <td><%= @product.orders.paid.count %></td>
        </tr>
        <tr>
          <td><%= icon 'money'  %> <strong>Ingresos generados:</strong></td>
          <td>$<%= @product.total_income %></td>
        </tr>
        <tr>
          <td><%= icon 'exclamation-triangle'  %> <strong>Deuda total:</strong></td>
          <td>$<%= @product.total_debt %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h3>Órdenes</h3>
    <%= render 'orders/order_table' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="btn-group" role="group">
      <%= link_to edit_product_path(@product), class: 'btn btn-primary' do %>
          <%= icon 'pencil-square-o' %> Editar
      <% end %>
      <%= link_to products_path, class: 'btn btn-default' do %>
          <%= icon 'cutlery' %> Volver
      <% end %>
      <%= link_to product_path(@product), class: 'btn btn-default', method: :delete, data: { confirm: '¿Estas seguro?' } do %>
          <%= icon 'trash-o' %> Eliminar
      <% end %>
    </div>
  </div>
</div>