config/routes.rb
Rails.application.routes.draw do

  resources :orders, except: [:show, :edit] do
    get 'historic', on: :collection
    get 'pay', on: :member
  end

  resources :products

  resources :customers

  root 'dashboard#index'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= icon 'cutlery', 'Breadly' %>
      <% end %>
      <p class="navbar-text">Tu desayuno durante Desafío Latam</p>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <%= icon 'shopping-cart', 'Órdenes' %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to orders_path do %>
                <%= icon 'exclamation-triangle', 'No pagadas' %> 
              <% end %>
            </li>
            <li>
              <%= link_to historic_orders_path do %>
                <%= icon 'check-square-o', 'Pagadas' %> 
              <% end %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to new_order_path do %>
                <%= icon 'shopping-cart', 'Nueva orden' %> 
              <% end %>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <%= icon 'cutlery', 'Productos' %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to products_path do %>
                <%= icon 'list-ul', 'Ver todos' %> 
              <% end %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to new_product_path do %>
                <%= icon 'cutlery', 'Nuevo producto' %> 
              <% end %>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <%= icon 'users', 'Clientes' %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to customers_path do %>
                <%= icon 'list-ul', 'Ver todos' %> 
              <% end %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to new_customer_path do %>
                <%= icon 'user', 'Nuevo cliente' %> 
              <% end %>
            </li>
          </ul>
        </li>
        <li>
          <button type="button" class="btn btn-primary navbar-btn" onclick='location.href="<%= new_order_path %>"'>
            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> &nbsp; Ingresar nueva orden
          </button>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_notice.html.erb
<% if flash[:notice] %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:notice] %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breadly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navbar' %>
  </header>

  <main class="container">
    <%= render 'layouts/notice' %>
    
    <div class="row">
      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= yield %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <%= render 'orders/stats' %>
      </div>
      </div>
  </main>

</body>
</html>